export enum PermissionKey {
  HOME_READ = 'HOME_READ',
  USERS_READ = 'USERS_READ',
  USER_READ = 'USER_READ',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  CONGREGATIONS_READ = 'CONGREGATIONS_READ',
  TAGS_READ = 'TAGS_READ',
  PROFILES_READ = 'PROFILES_READ',
  PROFILE_READ = 'PROFILE_READ',
  PROFILE_CREATE = 'PROFILE_CREATE',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
}
