export enum PermissionKey {
  HOME_READ = 'HOME_READ',
  USERS_READ = 'USERS_READ',
  CONGREGATIONS_READ = 'CONGREGATIONS_READ',
  TAGS_READ = 'TAGS_READ',
  PROFILES_READ = 'PROFILES_READ',
  PROFILE_READ = 'PROFILE_READ',
}
